version: '2'
services:
  php-fpm:
    image: php:5.6-fpm
    volumes:
      - E:/docker/multisite/www/:/var/www
  web1:
    build: ./web1    
    volumes:
      - E:/docker/multisite/www/web1/:/var/www/web1
    links:
      - php-fpm
  web2:
    build: ./web2
    volumes:
      - E:/docker/multisite/www/web2/:/var/www/web2
    links:
      - php-fpm
  web3:
    build: ./web3
    volumes:
      - E:/docker/multisite/www/web3/:/var/www/web3
    links:
      - php-fpm
  nginx:
    build: ./nginx
    volumes:
      - E:/docker/multisite/www/home/:/var/www/home
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-fpm
      - web1